### ISSUE TITLE
Semantic Issue - Problem running Example

### ISSUE THREAD

**Issue by OptTrader** [jconst/JCStockGraph#4]
Hey,

I tried to build the example after I cloned the repo and installed the pods. 2 issues related to CPTAnimation.m. Says "Semantic Issue - Too many arguments to function call, expected 0, have 3 - on both issues. How do I fix that?

![screenshot 2015-04-29 18 04 52](https://cloud.githubusercontent.com/assets/6761377/7388753/5128bd72-ee9a-11e4-8300-323c206dd605.png)

**Comment by shuijinliuxi** [comment]
I have also the same problem. How do I fix that?

**Comment by derjohng** [comment]
In my case, I met this issue that cause in cocoapods v0.36.x with coreplot. I downgrade  cocoapods to v0.35.x to make it work around temporarily.  
see Ref: http://stackoverflow.com/questions/28304017/cptanimation-m-too-many-arguments-to-function-call-expected-0-have-3

**Comment by OptTrader** [comment]
Thanks for your tip. How do I safely downgrade the dependency coreplot?

**Comment by derjohng** [comment]
sudo gem uninstall cocoapods
Remove v0.36 from list.

sudo gem install cocoapods -v 0.35
If you want to install 0.35.x
